services:
  primary:
    image: postgres:latest
    container_name: pg-primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: postgres
      
    volumes:
      - primary-data:/var/lib/postgresql/data
      - ./primary/init_primary.sh:/docker-entrypoint-initdb.d/init_primary.sh
    ports:
      - "5433:5432"
    networks:
      - pgcluster
 
  replica1:
    image: postgres:latest
    container_name: pg-replica1
    environment:
      POSTGRES_USER: replica    
      POSTGRES_PASSWORD: replica_pass
    volumes:
      - replica1-data:/var/lib/postgresql/data
      - ./replica1/recovery.sh:/docker-entrypoint-initdb.d/recovery.sh
    depends_on:
      - primary
    ports:
      - "5434:5432"      
    networks:
      - pgcluster
 
  replica2:
    image: postgres:latest
    container_name: pg-replica2
    environment:
      POSTGRES_USER: replica    
      POSTGRES_PASSWORD: replica_pass
    volumes:
      - replica2-data:/var/lib/postgresql/data
      - ./replica2/recovery.sh:/docker-entrypoint-initdb.d/recovery.sh
    depends_on:
      - primary
    ports:
      - "5435:5432"
    networks:
      - pgcluster
 
volumes:
  primary-data:
  replica1-data:
  replica2-data:
 
networks:
  pgcluster:
    external: true
