version: '3'
services:
  myapplication:
    image: mongodb/mongodb-community-server:latest
    container_name: mongoapp
    environment:
      - CONN_STR=mongodb://admin:my-secret-pw@mongodb:27017
    command: '/bin/bash -c "sleep 5; date; mongosh $$CONN_STR --eval \"show dbs;\""'
    depends_on:
      - mongodb
    networks:
      - my-docker-network
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=my-secret-pw
    volumes:
      - type: bind
        source: /root/mongodb/data
        target: /mongodb/data
    ports:
      - "27017:27017"
    networks:
      - my-docker-network

networks:
  my-docker-network:
    external: true